inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - "gemfiles/**/*"

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/ModuleLength:
  Exclude:
    - "lib/exception_notifier.rb"

Metrics/ClassLength:
  Exclude:
    - "test/**/*.rb"

Metrics/MethodLength:
  Exclude:
    - "lib/exception_notifier/email_notifier.rb"

Metrics/BlockLength:
  Exclude:
    - "lib/exception_notifier/email_notifier.rb"
